//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchParametrisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchParametrisation.MyStrings - Copy", typeof(MyStrings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в элементе.
        /// </summary>
        public static string ErrorInElement {
            get {
                return ResourceManager.GetString("ErrorInElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет параметра.
        /// </summary>
        public static string ErrorNoParameter {
            get {
                return ResourceManager.GetString("ErrorNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недоступен для записи в элементе.
        /// </summary>
        public static string ErrorParamDisabled {
            get {
                return ResourceManager.GetString("ErrorParamDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный тип параметра.
        /// </summary>
        public static string ErrorUnknownParamType {
            get {
                return ResourceManager.GetString("ErrorUnknownParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР параметризация выполнена!.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номера помещений прописаны для стен.
        /// </summary>
        public static string Result3dFinishing {
            get {
                return ResourceManager.GetString("Result3dFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номера по типам отделки прописаны для помещений.
        /// </summary>
        public static string ResultFinishing {
            get {
                return ResourceManager.GetString("ResultFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработано квартир.
        /// </summary>
        public static string ResultFlatography {
            get {
                return ResourceManager.GetString("ResultFlatography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено отзеркаленных элементов.
        /// </summary>
        public static string ResultMirroredCount {
            get {
                return ResourceManager.GetString("ResultMirroredCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено проёмов.
        /// </summary>
        public static string ResultOpeningsCount {
            get {
                return ResourceManager.GetString("ResultOpeningsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балкон.
        /// </summary>
        public static string RoomBalcony {
            get {
                return ResourceManager.GetString("RoomBalcony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спальная.
        /// </summary>
        public static string RoomBedroom {
            get {
                return ResourceManager.GetString("RoomBedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кухня.
        /// </summary>
        public static string RoomKitchen {
            get {
                return ResourceManager.GetString("RoomKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лоджия.
        /// </summary>
        public static string RoomLoggia {
            get {
                return ResourceManager.GetString("RoomLoggia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номера помещений в отделку.
        /// </summary>
        public static string Transaction3dFinishing {
            get {
                return ResourceManager.GetString("Transaction3dFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведомость отделки.
        /// </summary>
        public static string TransactionFinishing {
            get {
                return ResourceManager.GetString("TransactionFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартирография.
        /// </summary>
        public static string TransactionFlatography {
            get {
                return ResourceManager.GetString("TransactionFlatography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск отзеркаленных.
        /// </summary>
        public static string TransactionMirrored {
            get {
                return ResourceManager.GetString("TransactionMirrored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площади проемов.
        /// </summary>
        public static string TransactionOpeningsArea {
            get {
                return ResourceManager.GetString("TransactionOpeningsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string ValueCommentsParam {
            get {
                return ResourceManager.GetString("ValueCommentsParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_КоэффПлощади.
        /// </summary>
        public static string ValueFlatAreaCoeff {
            get {
                return ResourceManager.GetString("ValueFlatAreaCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_ПлощКвартиры.
        /// </summary>
        public static string ValueFlatAreaParam {
            get {
                return ResourceManager.GetString("ValueFlatAreaParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_ПлощКвЖилая.
        /// </summary>
        public static string ValueFlatLivingArea {
            get {
                return ResourceManager.GetString("ValueFlatLivingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_НомерКвартиры.
        /// </summary>
        public static string ValueFlatNumberParam {
            get {
                return ResourceManager.GetString("ValueFlatNumberParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_КолвоКомнат.
        /// </summary>
        public static string ValueFlatRoomsCount {
            get {
                return ResourceManager.GetString("ValueFlatRoomsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_ПлощКвОбщая.
        /// </summary>
        public static string ValueFlatSumAreaParam {
            get {
                return ResourceManager.GetString("ValueFlatSumAreaParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Л.
        /// </summary>
        public static string ValueMirroredText {
            get {
                return ResourceManager.GetString("ValueMirroredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_ПлощПроемов.
        /// </summary>
        public static string ValueOpeningAreaParam {
            get {
                return ResourceManager.GetString("ValueOpeningAreaParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота.
        /// </summary>
        public static string ValueOpeningHeightParam {
            get {
                return ResourceManager.GetString("ValueOpeningHeightParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        public static string ValueOpeningWidthParam {
            get {
                return ResourceManager.GetString("ValueOpeningWidthParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещение жилое.
        /// </summary>
        public static string ValueRoomIsLivingParam {
            get {
                return ResourceManager.GetString("ValueRoomIsLivingParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_НомераПомещенийВедОтделки.
        /// </summary>
        public static string ValueRoomNumberByFinishingType {
            get {
                return ResourceManager.GetString("ValueRoomNumberByFinishingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_НомераПомещенийПоТипуПола.
        /// </summary>
        public static string ValueRoomNumberByFloorType {
            get {
                return ResourceManager.GetString("ValueRoomNumberByFloorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АР_НомерПомещения.
        /// </summary>
        public static string ValueRoomNumberParam {
            get {
                return ResourceManager.GetString("ValueRoomNumberParam", resourceCulture);
            }
        }
    }
}
